"""
Email 發送模組

將日報內容格式化為專業的 HTML 信件，並透過 SMTP 寄出。
"""

import aiosmtplib
from email.message import EmailMessage
from datetime import datetime
import pytz
import re

from app.config import settings, log
from app.models import Newsletter


def _build_html_email(newsletter: Newsletter, market_data: dict) -> str:
    """將 Newsletter 資料轉換為美觀的 HTML Email 排版"""
    now = datetime.now(pytz.timezone(settings.timezone))
    date_str = now.strftime("%Y-%m-%d")
    
    html = f"""
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333333; background-color: #f4f6f9; margin: 0; padding: 20px; }}
            .container {{ max-width: 650px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }}
            .header {{ border-bottom: 2px solid #0056b3; padding-bottom: 15px; margin-bottom: 25px; }}
            .header h2 {{ color: #0056b3; margin: 0 0 5px 0; }}
            .header h3 {{ margin: 10px 0 0 0; color: #111; }}
            .market {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 30px; border-left: 4px solid #0056b3; }}
            .market p {{ margin: 5px 0; }}
            .section {{ margin-bottom: 35px; }}
            .section h4 {{ font-size: 1.1em; color: #0056b3; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
            blockquote {{ border-left: 4px solid #dee2e6; margin-left: 0; padding-left: 15px; color: #555555; font-style: italic; }}
            .sources {{ font-size: 0.9em; color: #666; margin-top: 10px; background: #fdfdfd; padding: 10px; border-radius: 5px; }}
            .sources ul {{ margin: 5px 0; padding-left: 20px; }}
            .footer {{ margin-top: 40px; font-size: 0.85em; color: #888888; border-top: 1px solid #eeeeee; padding-top: 20px; text-align: center; }}
            .footer blockquote {{ text-align: left; background: #fff8e1; border-left-color: #ffc107; padding: 15px; border-radius: 4px; font-style: normal; color: #333; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>📈 US Stock Newsletter</h2>
                <p style="color: #666; margin:0;">📅 {date_str}</p>
                <h3>🔥 {newsletter.subject}</h3>
            </div>
            
            <div class="market">
                <h4 style="margin-top:0;">📊 大盤指數快照</h4>
    """
    
    for sym, v in market_data.items():
        change_val = v.get("change", 0.0)
        arrow = "🟢" if change_val >= 0 else "🔴"
        color = "green" if change_val >= 0 else "red"
        price = v.get("price", 0)
        name = v.get("name", sym)
        html += f"<p>{arrow} <b>{name}</b> \t <code>{price:,.2f}</code> (<span style='color:{color}'>{change_val:+.2f}%</span>)</p>"
        
    if newsletter.market_summary:
        html += f"<p style='margin-top:15px;'>🗣️ <b>市場短評：</b></p><blockquote>{newsletter.market_summary}</blockquote>"
        
    html += "</div>"
    
    icons_list = ["🎯", "🔥", "💡", "📌", "⚡"]
    for idx, sec in enumerate(newsletter.sections):
        icon = icons_list[idx] if idx < len(icons_list) else "🔹"
        html += f"""
            <div class="section">
                <h4>{icon} {sec.title}</h4>
                <blockquote>{sec.body}</blockquote>
        """
        if sec.sources:
            html += '<div class="sources"><strong>🔗 消息來源：</strong><ul>'
            for s in sec.sources[:3]:
                title = getattr(s, "title", "查看原文")
                url = getattr(s, "url", "#")
                html += f'<li><a href="{url}" style="color: #0056b3; text-decoration: none;">{title}</a></li>'
            html += '</ul></div>'
        html += "</div>"
        
    html += f"""
            <div class="footer">
                <h4 style="text-align:left; color:#d32f2f;">🧭 投資啟示與風險</h4>
                <blockquote>{newsletter.insights}</blockquote>
                <p style="margin-top:20px;">⚠️ 免責聲明：本文內容僅供參考，不構成投資建議，入市須謹慎。</p>
                <p>🤖 <i>Generated by AI Agent</i></p>
            </div>
        </div>
    </body>
    </html>
    """
    
    # 轉換 【TICKER】 成為粗體
    html = re.sub(r'【([A-Z]{1,5})】', r'<b>\1</b>', html)
    return html


async def send_newsletter_to_email(newsletter: Newsletter, market_data: dict) -> None:
    """透過 SMTP 傳送 Email，如果環境變數未設定則自動跳過。"""
    if not all([settings.smtp_host, settings.smtp_port, settings.smtp_user, settings.smtp_pass, settings.email_recipient]):
        log.info("未設定完整的 SMTP 信箱變數，跳過發送 Email。")
        return
        
    log.info("準備發送 Email 至 %s...", settings.email_recipient)
    
    now = datetime.now(pytz.timezone(settings.timezone))
    date_str = now.strftime("%Y-%m-%d")
    
    msg = EmailMessage()
    msg["Subject"] = f"📈 美股日報 ({date_str}) - {newsletter.subject}"
    msg["From"] = f"US Stock Bot <{settings.smtp_user}>"
    msg["To"] = settings.email_recipient
    
    html_content = _build_html_email(newsletter, market_data)
    msg.set_content("請使用支援 HTML 的郵件客戶端查看此信件。")
    msg.add_alternative(html_content, subtype="html")
    
    try:
        await aiosmtplib.send(
            msg,
            hostname=settings.smtp_host,
            port=settings.smtp_port,
            username=settings.smtp_user,
            password=settings.smtp_pass,
            use_tls=settings.smtp_port == 465,
            start_tls=settings.smtp_port == 587,
            timeout=15.0,
        )
        log.info("✅ 美股日報 Email 發送成功！")
    except Exception as e:
        log.error("❌ 發送 Email 失敗: %s", e)
