"""
HTML 格式化工具

用於轉換資料成可供 Telegram HTML Parse Mode 呈現的文字。
"""

import re
from datetime import datetime

# Regex 用於捕獲 【TICKER】格式
_TICKER_RE = re.compile(r'【([A-Z]{1,5})】')


def escape_html(text: str) -> str:
    """跳脫 HTML 特殊字元防止 Telegram 解析錯誤。"""
    if not text:
        return ""
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def highlight_ticker(body: str) -> str:
    """轉換 【NVDA】 標記為 Telegram 加粗標籤 <b>NVDA</b>。"""
    if not body:
        return ""
    return _TICKER_RE.sub(r'<b>\1</b>', body)


def get_trend_arrow(change: float) -> str:
    """根據漲跌加上表情符號。"""
    return "📈" if change >= 0 else "📉"


def build_header(subject: str, now: datetime) -> str:
    """產生開頭主旨段落。"""
    weekday = ["一", "二", "三", "四", "五", "六", "日"][now.weekday()]
    date_str = now.strftime(f"%Y-%m-%d（週{weekday}）")
    return (
        "📈 <b>US Stock Newsletter</b>\n"
        f"<blockquote>📅 {date_str}</blockquote>\n\n"
        f"🔥 <b>{escape_html(subject)}</b>"
    )


def build_market_card(market: dict, summary: str) -> str:
    """產生大盤快照段落。"""
    lines = ["📊 <b>大盤指數快照</b>", ""]
    
    for sym, v in market.items():
        change_val = v.get("change", 0.0)
        arrow = "🟢" if change_val >= 0 else "🔴"
        change_str = f"{change_val:+.2f}%"
        price_val = v.get("price", 0.0)
        
        name = escape_html(v.get('name', sym))
        lines.append(
            f"{arrow} <b>{name}</b> <code>{price_val:,.2f}</code> (<i>{change_str}</i>)"
        )
        
    if summary:
        lines += ["\n🗣️ <b>市場短評：</b>", f"<blockquote>{escape_html(summary)}</blockquote>"]
        
    return "\n".join(lines)


def build_section_block(idx: int, title: str, body: str, sources: list) -> str:
    """產生單個章節段落。"""
    icons = ["🎯", "🔥", "💡", "📌", "⚡"]
    icon = icons[idx] if idx < len(icons) else "🔹"
    
    title_safe = escape_html(title)
    body_safe = highlight_ticker(escape_html(body))
    
    # 使用 blockquote 讓正文有很好的層次感
    text = f"{icon} <b>{title_safe}</b>\n<blockquote>{body_safe}</blockquote>"
    
    if sources:
        text += "🔗 <b>消息來源:</b> "
        links = []
        for i, s in enumerate(sources[:3], 1):
            label = escape_html(getattr(s, "title", "來源")).strip()
            # 太長的標題進行截斷
            if len(label) > 15:
                label = label[:14] + ".."
            
            url = getattr(s, "url", "")
            if url:
                links.append(f'<a href="{url}">[{i}] {label}</a>')
        
        if links:
            text += " | ".join(links)
                
    return text


def build_footer(insights: str) -> str:
    """產生底部免責與投資啟示。"""
    insights_safe = highlight_ticker(escape_html(insights))
    return (
        f"🧭 <b>投資啟示與風險</b>\n<blockquote>{insights_safe}</blockquote>\n\n"
        f"⏤⏤⏤⏤⏤⏤⏤⏤⏤⏤⏤⏤\n"
        f"<i><tg-spoiler>⚠️ 免責聲明：本文內容僅供參考，不構成投資建議，入市須謹慎。</tg-spoiler></i>"
        f"\n🤖 <i>Generated by AI Agent</i>"
    )
